# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
#platform :iOS, '10.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'MyWeatherApp' do
 pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'
end

